### ISSUE TITLE
Build failure on windows after commit 6bfc2c7

### ISSUE THREAD

**Issue by okleitsa** [prometheus/procfs#111]
Build output:

vendor\github.com\prometheus\procfs\internal\util\parse.go:79:28: cannot use int(f.Fd()) (type int) as type syscall.Handle in argument to syscall.Read

**Comment by jonnenauha** [comment]
Please fix this asap. These are no tags or "stable" branches in this repo. This is breaking builds all over the place that include prometheus golang client. Not having tags will force people to disable windows builds or vendor the whole repo just to remove it when this is fixes.

Maybe should use some other branch than master to do dev and run tests.

**Comment by okleitsa** [comment]
I'm importing client_golang and using dep (still). This means that procfs is a transitive dependency to my project and thus will only get the required packages. So client_golang requires procfs package which in turns requires xfs and nfs packages which, finally, require the util package.

So, moving this function (which is OS-specific if I understand correctly) to the util package, makes every attempt to build to another OS unsuccessful.

I hope that was helpful.

**Comment by SuperQ** [comment]
I would appreciate some help from some more experienced Windows developers.

One thing I'm thinking about is how does the [processCollector](https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go) work on Windows?

Does this bit of code work at all? Perhaps we can fix the dependency tree there, so that on windows it doesn't use any Linux-specific stuff like procfs.

**Comment by jonnenauha** [comment]
@SuperQ as described, this seems to break all builds that fetch latest prometheus go client.

If you don't yet know how to fix it properly, please revert the commit. Do the change later when you figure it out.

Do this to fix this now:
```
git revert 6bfc2c70c4ee6da6946888bb96dec33f825df32b
git push origin/master
```

When you try again locally, just run `GOOS=windows go build` in this repos folder to test if the bug is fixes, you will get what was reported in the first message. You don't need access to windows to figure this out.

**Comment by beorn7** [comment]
> One thing I'm thinking about is how does the processCollector work on Windows?

It doesn't report metrics, but an error. The code in question is https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go#L128-L135 .

Thus, it depends on the `NewStat` constructor to return an error on platforms that aren't covered by prometheus/procfs. The latter should have all the build guards to not try anything on (e.g.) MS Windows that wouldn't compile.

**Comment by beorn7** [comment]
I think the problem is that the `sysfs` package wouldn't work on MS Windows but wasn't used by any binaries meant for MS Windows. Now `SysReadFile` got moved into the `util` package, which _is_ used by binaries meant to be built for MS Windows. I would just not move it into the general `util` package. (Am I missing a reason for doing so?)

**Comment by SuperQ** [comment]
@beorn7 The reason to move it to the internal/util package was to make it more useful across the procfs package.

IMO, the problem here is we don't have a platform-specific setup for client_golang's process collector.

**Comment by beorn7** [comment]
client_golang is not the only user of this repo. I don't think all users of this repo should pull up the information on which platform it works and on which not. This should only be maintained at one place, which is here in the repo. Currently, the API works in a way that you call `NewStats` and check the error to see if the process stats are supported on your platform. It would be a breaking change to change that to "the package doesn't compile and you need build tags to guard its usages".

**Comment by beorn7** [comment]
For now, I'd just not move SysReadFile into the util package. You are not yet using in anywhere outside of the sysfs package. Perhaps discuss a possible change with @grobie when he is back.

**Comment by SuperQ** [comment]
Ok.  I'm setting up a test matrix on Travis right now so we can verify the change works.

**Comment by SuperQ** [comment]
I've finished the test matrix, and refactoring the code.

https://github.com/prometheus/procfs/pull/112

**Comment by SuperQ** [comment]
Ok, please test your windows builds with the latest commit. Sorry for the breakage, we now have a CI test to prevent this in the future. :smile:

**Comment by okleitsa** [comment]
All good. Thank you!
