### ISSUE TITLE
Not working with Go Get

### ISSUE THREAD

**Issue by Colhodm** [prometheus/procfs#221]
Hi,
Trying to use go get and compile, but getting complaints from the commit that went in a day ago:
./cpuinfo.go:58:15: undefined: util.ReadFileNoStat
./ipvs.go:70:15: undefined: util.ReadFileNoStat
./proc.go:125:15: undefined: util.ReadFileNoStat
./proc.go:139:15: undefined: util.ReadFileNoStat
./proc_environ.go:26:15: undefined: util.ReadFileNoStat
./proc_fdinfo.go:48:15: undefined: util.ReadFileNoStat
./proc_io.go:46:15: undefined: util.ReadFileNoStat
./proc_psi.go:60:15: undefined: util.ReadFileNoStat
./proc_stat.go:116:15: undefined: util.ReadFileNoStat
./proc_status.go:78:15: undefined: util.ReadFileNoStat
./proc_status.go:78:15: too many errors
Thanks!

**Comment by pgier** [comment]
Are you getting those errors doing a `go get github.com/prometheus/procfs`?  I tried this after deleting the existing procfs dir and cleaning my local module cache `go clean --modcache`, and I didn't see any errors.

The new ReadFileNoStat function is in the internal.util package.  Do you see this in your procfs directory?

**Comment by Colhodm** [comment]
Hi,
The function is defined in the util package, and is present in the code written in `sysreadfile.go`. So the source code looks all fine, so I'm not sure why it is unable to resolve the import path for util.

**Comment by dmitshur** [comment]
The problem is in PR #219. It added `ReadFileNoStat` to [internal/util/sysreadfile.go](https://github.com/prometheus/procfs/blob/c0c2a8be4d30a2e2cb95ea371a6f32a506d3e45e/internal/util) but not to [internal/util/sysreadfile_compat.go](https://github.com/prometheus/procfs/blob/c0c2a8be4d30a2e2cb95ea371a6f32a506d3e45e/internal/util/sysreadfile_compat.go). I left a comment [here](https://github.com/prometheus/procfs/pull/219#pullrequestreview-297853444).

**Comment by pgier** [comment]
Sorry about that, I have created #222 to hopefully fix this.
