### ISSUE TITLE
Stats.NumThreads gives wrong value

### ISSUE THREAD

**Issue by stgleb** [prometheus/procfs#25]
I'm using procfs for observing number of threads spawned by current process and simultaneously looking to procfs by simple cat /proc/<pid>/status|grep Thread.
When count of threads if pretty low (under 100) results are the same. But when accoring to data extracted by cat from proc are pretty high (a few hundreds) then procfs library gives me 0. What is the reason of such inconsistency?

Source code can be found [here](https://github.com/stgleb/thread_count_observer)

**Comment by pgier** [comment]
Running the example code, I wasn't able to reproduce the issue.  The only things I can think of that may have caused this are (1) maybe there was some difference on your system between `/proc/<pid>/stat` (which is read by procfs) and `/proc/<pid>/status` (which you were comparing) or (2) maybe there was a bug in the golang `fmt.Fscan` function which caused the integer to be read incorrectly.

If you are still able to reproduce this issue, I can take a deeper look, otherwise I'll close the issue.
