### ISSUE TITLE
Consolidate fixtures structure

### ISSUE THREAD

**Issue by grobie** [prometheus/procfs#43]
So the current fixtures structure doesn't make too much sense. It's mixing "root" level files/folders like `stat` with special purpose subdirectories (like `buddyinfo/short/buddinfo`). I was thinking about moving all "root" files into a `default` subdirectory so that we'd end up with `fixtures/{default,specialcasedir,likebuddyinfo}/actualpath`. Given we support now both procfs and sysfs, maybe it should become `fixtures/{proc,sys}/{default,special,otherspecial}/...`?

@mdlayher wdyt?

**Comment by mdlayher** [comment]
I like your idea of doing `fixtures/{proc,sys}` instead of hacking in another `fixtures/` like I did for `sysfs`.

I didn't realize there were "malformed" fixtures in the folder.  To me, it makes the most sense to:
- have malformed data present inline with the tests (and use it to test the internal parsing functions)
- have correct data present in fixture files (and use it to test the path traversal _and_ parsing functions)

As a brief example:

```go
func TestBuddyinfoMalformed(t *testing.T) {
    // Only tests internal parsing functions
    r := strings.NewReader("broken")
    if err := parseBuddyInfo(r); err == nil {
        t.Fatal("should fail parsing")
    }
}

func TestBuddyinfoOK(t *testing.T) {
    // Calls "parseBuddyInfo" internally, but also tests file/directory
    // access against known good fixture
    fs := NewFS("fixtures")
    info, err := fs.BuddyInfo()
    // ...
}
```

This is also the approach I took with the XFS stats parsing: https://github.com/prometheus/procfs/blob/master/xfs/parse_test.go.

Thoughts?

**Comment by mdlayher** [comment]
I think I hinted at this, but I'd like to explicitly mention that whatever lives under `fixtures/{proc,sys}` should actually exist in a real Linux system.
